### PR TITLE
ft Trip statistics #181414582

### PR DESCRIPTION
**Pull request by NNesta**
**1. Name of the Task**
Users should get stats of trips made in the last X timeframe

**2. Pivot Track ID**
[
181414583](https://www.pivotaltracker.com/story/show/181414582)
**3. Branch Name**
trip-statistics-#181414582

**4 Task Description**

Why
As an authenticated user, I should get the stats in terms of number of trips made in the last months, days, weeks etc.

Managers and travellers should get detailed statistics of the number of trips he/she has made in the recent past

** 5 How can be it tested**

Given that the user is logged in and has accessed the dashboard clicj the statistics link then he become redirected to statistics page

### CODE REVIEW

**Review by iyaremye-faustin — DISMISSED** [review]
Working

**Review by iyaremye-faustin — DISMISSED** [review]
Working

**Review by mucyoalexaxel — DISMISSED** [review]
Good Work @NNesta

**Review by rukundo-kevin — DISMISSED** [review]

**Review by iyaremye-faustin — APPROVED** [review]
Working

**Pull request merged**
