### PR TITLE
ch-set-up-tests-#181414552

### PR DESCRIPTION
**Pull request by SergeNm**
## What does this PR do? 
 - Set up tests on the client
 
## Description of task
We are going to use Jest to write unit tests for our components in react as well as integration tests for the various pages on our client. Setup the Jest library and add any commands required for testing in the README of the project.

## How to test this PR?
- yarn install
- yarn test

### CODE REVIEW

**Review by rukundo-kevin — DISMISSED** [review]
The test setup is okay, But rebase your work

**Review by iyaremye-faustin — DISMISSED** [review]
Good work

**Comment by iyaremye-faustin** [comment]
Please rebase to resolve conflicts

**Review by mucyoalexaxel — APPROVED** [review]
Nice Work @SergeNm .

**Review by NNesta — APPROVED** [review]
Good job

**Review by EmyRukundo — APPROVED** [review]

**Pull request merged**
