### PR TITLE
#181414560 Feat: Implement user Registration

### PR DESCRIPTION
**Pull request by rukundo-kevin**
# 1. Name of task
- Implement Signup/Register 
# 2. Pivot Tracker ID
-[ #181414560](https://www.pivotaltracker.com/story/show/181414560)

# 3. Branch Name
- `ft-register-181414560 `
# 4. Description of task
**Why**
To be able to use the application and access authenticated routes, Users should be able to Signup and or Register using  Sign up forms on the signup route.

**Acceptance Criteria**

**GIVEN** user successfully signs up/registers.
**WHEN** user passes appropriate signup parameters 
**THEN** user should be able to sign up.
# 7. How can PR be tested.

Navigate to the terminal and start the server,
- go to the register route on your browser.
- Change the baseURL in `src/api/index.js`
- Go to the browser and you are ready to test the server

Screen Shot 2022-05-20 at 12 25 59

### CODE REVIEW

**Review by iyaremye-faustin — COMMENTED** [review]
Good job but no message showing on successful signup, add a message and clears form inputs

**Review by mucyoalexaxel — COMMENTED** [review]
@rukundo-kevin Remove `.DS_Store` in the root directory and also in `src/.DS_Store` . 
and Good Job.

**Review by mucyoalexaxel — DISMISSED** [review]
LGTM

**Review by SergeNm — APPROVED** [review]

**Review by NNesta — APPROVED** [review]
Good job

**Pull request merged**
